site_name: finice
repo_url: https://github.com/bnaard/finice
site_url: https://bnaard.github.io/finice
site_description: A finance planning app
site_author: Bernhard Gerlach
edit_uri: edit/main/docs/
repo_name: bnaard/finice
copyright: Maintained by <a href="https://bnaard.com">bnaard</a>.

nav:
  - Home: index.md
  - Modules: modules.md
  - Development Environment: devenv.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [app]
theme:
  name: material
  feature:
    tabs: true
  features:
    - content.code.copy
    - content.code.select
    - content.code.annotate
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github
  logo: assets/refinice_logo.svg
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/bnaard/finice
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/finice

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
