version: "3"

networks:
  backend:
    ipam:
      driver: default
      config:
        - subnet: "192.168.0.1/24"
  database:
    ipam:
      driver: default
      config:
        - subnet: "192.168.1.1/24"

services:
  backend:
    container_name: nicegui-backend
    build:
      context: .
      dockerfile: backend.prod.Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    ports:
      - 8080:8080
    networks:
      - backend
    user: vscode

  database:
    image: dolthub/dolt-sql-server
    container_name: dolt-server
    volumes:
      - ../data:/var/lib/dolt/                       # data directory mapping
      # - ../cfg/dolt-server:/etc/dolt/servercfg.d     # server configuration file mapping
      - ../cfg/dolt:/etc/dolt/doltcfg.d              # global dolt configuration mapping
    ports:
      - 3307:${DATABASE_PORT}
    networks:
      - backend
      - database
    environment:
      - DOLT_HOST=${DATABASE_HOST}
      - DOLT_PORT=${DATABASE_PORT}
      - DOLT_USER=${DATABASE_USER}
      - DOLT_PASSWORD=${DATABASE_PASSWORD}
      - DOLT_TIMEOUT=${DATABASE_TIMEOUT}
      - DOLT_LOGLEVEL=${DATABASE_LOGLEVEL}
    command: dolt sql-server --host=${DATABASE_HOST} --port=${DATABASE_PORT} --user=${DATABASE_USER} --password=${DATABASE_PASSWORD} --timeout=${DATABASE_TIMEOUT} --loglevel=${DATABASE_LOGLEVEL}

  workbench:
    image: dolthub/dolt-workbench
    container_name: dolt-workbench
    volumes:
      - ../cfg/dolt-workbench:/app/graphql-server/store
    ports:
      - 9002:9002
      - 3000:3000
    networks:
      - database
